apiVersion : apps/v1
kind: Deployment
metadata:
  name: "akstest-9ac0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "akstest-9ac0"
  template:
    metadata:
      labels:
        app: "akstest-9ac0"
    spec:
      containers:
        - name: "akstest-9ac0"
          image: "sabbour.azurecr.io/akstest"
          ports:
          - containerPort: 80