replicaCount: 1
image:
  pullPolicy: Always
service:
  internalPort: 80
  externalPort: 80
ingress:
  enabled: true
  basedomain:  cc52d3f9-e6e0-4e9d-82fe-882ad68bf09a.westus.aksapp.io # replace with your own from the portal