replicaCount: 1
image:
  pullPolicy: Always
service:
  internalPort: 3000
  externalPort: 80
ingress:
  enabled: true
  basedomain: 198178d78e5a4b289ba8.northeurope.aksapp.io # replace with your own from the portal